# Generated by Django 4.1.7 on 2023-04-02 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='pt_name',
            field=models.CharField(default='Clareamento dental', max_length=100, verbose_name='PT Name'),
            preserve_default=False,
        ),
    ]
