# Generated by Django 4.1.7 on 2023-04-05 16:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='confirmation_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Confirmation token'),
        ),
    ]
