# Generated by Django 4.1.7 on 2023-04-08 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_customschedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='procedure',
            old_name='pt_name',
            new_name='name_pt',
        ),
    ]
